
package serverWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotaryWebServiceImplService", targetNamespace = "http://Implementacao.ws/", wsdlLocation = "http://localhost:9898/notaryService?wsdl")
@HandlerChain(file="binas-ws_handler-chain-binding.xml")
public class NotaryWebServiceImplService
    extends Service
{

    private final static URL NOTARYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTARYWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName NOTARYWEBSERVICEIMPLSERVICE_QNAME = new QName("http://Implementacao.ws/", "NotaryWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9898/notaryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTARYWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        NOTARYWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public NotaryWebServiceImplService() {
        super(__getWsdlLocation(), NOTARYWEBSERVICEIMPLSERVICE_QNAME);
    }

    public NotaryWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTARYWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public NotaryWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, NOTARYWEBSERVICEIMPLSERVICE_QNAME);
    }

    public NotaryWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTARYWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public NotaryWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotaryWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotaryWebService
     */
    @WebEndpoint(name = "NotaryWebServiceImplPort")
    public NotaryWebService getNotaryWebServiceImplPort() {
        return super.getPort(new QName("http://Implementacao.ws/", "NotaryWebServiceImplPort"), NotaryWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotaryWebService
     */
    @WebEndpoint(name = "NotaryWebServiceImplPort")
    public NotaryWebService getNotaryWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Implementacao.ws/", "NotaryWebServiceImplPort"), NotaryWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTARYWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw NOTARYWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return NOTARYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
