
package clientWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientWebServiceImplService", targetNamespace = "http://impl.ws/", wsdlLocation = "http://localhost:9090/user0WebService?wsdl")
public class ClientWebServiceImplService
    extends Service
{

    private final static URL CLIENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CLIENTWEBSERVICEIMPLSERVICE_QNAME = new QName("http://impl.ws/", "ClientWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/user0WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CLIENTWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ClientWebServiceImplService() {
        super(__getWsdlLocation(), CLIENTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ClientWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ClientWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ClientWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ClientWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClientWebServiceImpl
     */
    @WebEndpoint(name = "ClientWebServiceImplPort")
    public ClientWebServiceImpl getClientWebServiceImplPort() {
        return super.getPort(new QName("http://impl.ws/", "ClientWebServiceImplPort"), ClientWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientWebServiceImpl
     */
    @WebEndpoint(name = "ClientWebServiceImplPort")
    public ClientWebServiceImpl getClientWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws/", "ClientWebServiceImplPort"), ClientWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CLIENTWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CLIENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
