
package sec.notary.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotaryWebService", targetNamespace = "http://server.notary.sec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotaryWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://server.notary.sec/", className = "sec.notary.client.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://server.notary.sec/", className = "sec.notary.client.TestResponse")
    @Action(input = "http://server.notary.sec/NotaryWebService/testRequest", output = "http://server.notary.sec/NotaryWebService/testResponse")
    public String test(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
