
package sec.notary.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotaryWebServiceService", targetNamespace = "http://server.notary.sec/", wsdlLocation = "http://localhost:9898/notaryService?wsdl")
public class NotaryWebServiceService
    extends Service
{

    private final static URL NOTARYWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTARYWEBSERVICESERVICE_EXCEPTION;
    private final static QName NOTARYWEBSERVICESERVICE_QNAME = new QName("http://server.notary.sec/", "NotaryWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9898/notaryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTARYWEBSERVICESERVICE_WSDL_LOCATION = url;
        NOTARYWEBSERVICESERVICE_EXCEPTION = e;
    }

    public NotaryWebServiceService() {
        super(__getWsdlLocation(), NOTARYWEBSERVICESERVICE_QNAME);
    }

    public NotaryWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTARYWEBSERVICESERVICE_QNAME, features);
    }

    public NotaryWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, NOTARYWEBSERVICESERVICE_QNAME);
    }

    public NotaryWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTARYWEBSERVICESERVICE_QNAME, features);
    }

    public NotaryWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotaryWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotaryWebService
     */
    @WebEndpoint(name = "NotaryWebServicePort")
    public NotaryWebService getNotaryWebServicePort() {
        return super.getPort(new QName("http://server.notary.sec/", "NotaryWebServicePort"), NotaryWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotaryWebService
     */
    @WebEndpoint(name = "NotaryWebServicePort")
    public NotaryWebService getNotaryWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.notary.sec/", "NotaryWebServicePort"), NotaryWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTARYWEBSERVICESERVICE_EXCEPTION!= null) {
            throw NOTARYWEBSERVICESERVICE_EXCEPTION;
        }
        return NOTARYWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
